---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: secrets-provider
spec:
  provider: azure
  secretObjects:
  - data:
    - key: tls.key
      objectName: mlops-tls
    - key: tls.crt
      objectName: mlops-tls
    secretName: mlops-tls
    type: kubernetes.io/tls
  parameters:
    keyvaultName: ml-ps-vlst
    objects: |
      array:
        - |
          objectName: mlops-tls
          objectType: secret
    useVMManagedIdentity: "true"
    userAssignedIdentityID: b868a679-b3be-4f77-9014-fe2ac6bb7938
    tenantId: b9d69197-ce1f-4907-9545-b307af2335e9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secrets
  labels:
    app: secrets
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secrets
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: secrets
    spec:
      containers:
      - args:
        - infinity
        command:
        - sleep
        image: docker.io/library/alpine:3.12.1
        name: secrets
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
          requests:
            cpu: 10m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        volumeMounts:
        - mountPath: /mnt/secrets-store
          name: secrets-store-inline
          readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      volumes:
      - csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: secrets-provider
        name: secrets-store-inline
---