name: ML Pipeline

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  ml-pipeline:
    name: Train, Evaluate and Deploy ML Model
    runs-on: ubuntu-latest

    env:
      AZURE_STORAGE_ACCOUNT: mlstoregs
      AZURE_STORAGE_CONTAINER: mlops
      DATASET_NAME: customer_churn.csv
      MLFLOW_TRACKING_URI: "http://mlflow-mlflow.mlflow.svc.cluster.local:5000"
      MLFLOW_EXPERIMENT: customer-churn
      REGISTERED_MODEL_NAME: customer-churn-model
      MODEL_ALIAS: Production
      KUBEFLOW_ENDPOINT: ${{ secrets.KUBEFLOW_ENDPOINT }}
      KUBEFLOW_EXPERIMENT_NAME: customer-churn-experiment
      KSERVE_NAMESPACE: mlops
      INFERENCE_SERVICE_NAME: customer-churn
      MIN_ACCURACY: "0.80"
      MIN_PRECISION: "0.75"
      MIN_RECALL: "0.75"
      MIN_F1: "0.75"

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0

    - name: Install Azure CLI
      run: |
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

    - name: Install Kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Login To Azure
      run: |
        echo "Logging into Azure with service principal..."
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        echo "Azure login successful"

    - name: Login To AKS
      uses: azure/aks-set-context@v5
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        cluster-name: ${{ secrets.CLUSTER_NAME }}
        admin: true

    - name: Docker Login
      uses: docker/login-action@v4
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      
    - name: Backend Build And Push
      uses: docker/build-push-action@v7
      with:
        context: ./ml
        push: true
        no-cache: true
        tags: ${{ secrets.DOCKER_REGISTRY }}/mlflow:${{github.run_number}}

    - name: Set ML Pipeline Base Image
      shell: bash
      run: |
        echo "ML_PIPELINE_BASE_IMAGE=${{ secrets.DOCKER_REGISTRY }}/mlflow:${{ github.run_number }}" >> "$GITHUB_ENV"

    - name: Deploy RBAC
      working-directory: pipeline
      run: |
        kubectl apply -f rbac.yaml
  
    - name: Install Dependencies
      shell: bash
      working-directory: pipeline
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt   
    
    - name: Compile Kubeflow Pipeline
      shell: bash
      working-directory: pipeline
      run: |
        python compile_pipeline.py

    - name: Trigger Kubeflow Pipeline
      shell: bash
      working-directory: pipeline
      run: |
        python trigger_pipeline.py